version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      day: 'sunday'
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/.storybook'
    schedule:
      day: 'sunday'
      interval: 'weekly'
